/*
 * Moje API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.BikeRentCreateRequest;
import io.swagger.client.model.BikeRentResponse;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for BikeRentApi
 */
@Ignore
public class BikeRentApiTest {

    private final BikeRentApi api = new BikeRentApi();

    /**
     * Create a new bike rent
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createBikeRentTest() throws Exception {
        BikeRentCreateRequest body = null;
        BikeRentResponse response = api.createBikeRent(body);

        // TODO: test validations
    }
    /**
     * Get all bike rents
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAllBikeRentsTest() throws Exception {
        List<BikeRentResponse> response = api.getAllBikeRents();

        // TODO: test validations
    }
}
