/*
 * Moje API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.BikeRentResponse;
import io.swagger.client.model.BikeRentUpdateRequest;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * Delete a bike rent
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteBikeRentTest() throws Exception {
        UUID id = null;
        api.deleteBikeRent(id);

        // TODO: test validations
    }
    /**
     * Update a bike rent
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateBikeRentTest() throws Exception {
        BikeRentUpdateRequest body = null;
        UUID id = null;
        BikeRentResponse response = api.updateBikeRent(body, id);

        // TODO: test validations
    }
}
